export const APP_LOGOUT = "APP_LOGOUT";
export const APP_LOGIN = "APP_LOGIN";

export const FETCH_ALL_PROJECTS_REALM = "FETCH_ALL_PROJECTS_REALM";
export const SEARCH_PROJECTS = "SEARCH_PROJECTS";
export const CLEAR_PROJECTS = "CLEAR_PROJECTS";

export const FETCH_USER_DETAILS_REALM = "FETCH_USER_DETAILS_REALM";
export const SAVE_USER_DETAILS_REALM = "SAVE_USER_DETAILS_REALM";
export const CLEAR_USER_DETAILS = "CLEAR_USER_DETAILS";

export const SET_SHOW_OPTIONS = 'SET_SHOW_OPTIONS';

export const SET_NOTES = 'SET_NOTES';
export const SET_LABELS = 'SET_LABELS';
export const SET_CEILING_HEIGHTS = 'SET_CEILING_HEIGHTS'
export const SET_TEXTURES = 'SET_TEXTURES';
export const DELETE_ROOM_OPTIONS = 'DELETE_ROOM_OPTIONS';
export const TOGGLE_CARPENTRY_VISIBLE = 'TOGGLE_CARPENTRY_VISIBLE';
export const TOGGLE_ELECTRICAL_VISIBLE = 'TOGGLE_ELECTRICAL_VISIBLE';
export const TOGGLE_PLUMBING_VISIBLE = 'TOGGLE_PLUMBING_VISIBLE';
export const SET_CHILDREN_ELEMENTS = 'SET_CHILDREN_ELEMENTS';
export const SET_POSITIONS = 'SET_POSITIONS';
export const SET_LAST_SCALE = 'SET_LAST_SCALE';
export const SET_CEILING_TYPE = 'SET_CEILING_TYPE'
export const TOGGLE_BOTTOM_VISIBLITY_FLAGS = 'TOGGLE_BOTTOM_VISIBLITY_FLAGS';
export const SET_FLIP_ITEM = 'SET_FLIP_ITEM';
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const SET_CATHEDRAL_CEILING_HEIGHT = 'SET_CATHEDRAL_CEILING_HEIGHT'
export const SET_ITEM_MATERIAL = 'SET_ITEM_MATERIAL';
export const SET_TILE_TOOL = 'SET_TILE_TOOL';
export const SET_ITEMS_BELONGS_TO = 'SET_ITEMS_BELONGS_TO'
export const SET_CURRENT_DIMENSIONS = 'SET_CURRENT_DIMENSIONS';
export const UPDATE_OPTION = 'UPDATE_OPTION';

export const SAVE_PROJECT = 'SAVE_PROJECT';
export const GET_PROJECT_STATE = 'GET_PROJECT_STATE';
export const UPLOAD_CUSTOM_LOGO = 'UPLOAD_CUSTOM_LOGO';
export const SAVE_PROJECT_STATE = 'SAVE_PROJECT_STATE';
export const TOGGLE_PDF_LOADER = 'TOGGLE_PDF_LOADER';

export const SET_ARTBOARD_DRAGGABLE = 'SET_ARTBOARD_DRAGGABLE';
// Own Code
export const SET_SNAP_GRID_X = 'SET_SNAP_GRID_X';
export const SET_SNAP_GRID_Y = 'SET_SNAP_GRID_Y';
export const RESET_SNAP_GRID_XY = 'RESET_SNAP_GRID_XY';